services:
  backend:
    build: ./backend
    container_name: dataanalyzer-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: dataanalyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
